### ISSUE TITLE
UX, minor: Profile link in dashboard takes me to empty profile with no button to get back

### ISSUE THREAD

**Issue by timmc** [nanote-co/issues#10]
Using the back button isn't so bad, but it's jarring and a little confusing.

**Comment by kevwu** [comment]
The profiles are meant to be a bit separate from the user's dashboard - they're independent mini-sites similar to how Tumblr user blogs are separate from the Tumblr dashboard. That said, it is indeed unexpected that the profile would go to an external page when the other header links all go to dashboard links. Would an external link icon or opening in the profile in a new tab be sufficiently clear?

**Comment by kevwu** [comment]
Clicking the profile link will now open your profile in a new tab. Hopefully this makes more sense. If it doesn't and/or you think there's a better solution, feel free to reopen this issue.

**Comment by timmc** [comment]
Makes sense. I'll open a separate issue for some other confusion around it.
