### ISSUE TITLE
"Profile" link is confusing when empty (also maybe misnamed)

### ISSUE THREAD

**Issue by timmc** [nanote-co/issues#18]
When I originally clicked the "profile" link in dashboard, I expected to be taken to one of two pages:

- A public page where my name, contact info, bio, etc. would be displayed (although all blank, since it's a new account), or
- A dashboard page where I could edit the former.

I wasn't expecting a page listing my posts -- and it was empty, since I didn't have any posts. Two thoughts:

- Maybe it should have a different name, like "my site" or "my public posts" or some such
- When empty perhaps there should be a bit of text saying "no public posts"

**Comment by kevwu** [comment]
I've improved the appearance of the profile page to make its purpose more obvious. I'm closing this for now; I'll reopen it if there are more similar complaints.
