### ISSUE TITLE
Cannot add a note to a category

### ISSUE THREAD

**Issue by timmc** [nanote-co/issues#24]
I can type an existing category's name in the category field on a note's settings, but I can't figure out how to select and add it to the note.

**Comment by kevwu** [comment]
Once autocomplete fills in the name of the category, pressing enter will add that category to the note.

I will add a message to make this more obvious and consider redesigning that section.

**Comment by kevwu** [comment]
A message has been added to make this more clear. If this still seems unintuitive feel free to reopen the issue.
