### ISSUE TITLE
It is unexpected that all categories are public

### ISSUE THREAD

**Issue by timmc** [nanote-co/issues#31]
If I write a private note and categorize it, I might not expect those categories to be world-visible on th eprofile. A couple possibilities:

- Make it very clear in the UI that all categories are public
- Only list categories used on public posts

**Comment by kevwu** [comment]
For now, the names of categories are world-visible. There are plans for permissions on categories but they are not yet set in stone or implemented. For now, I will add a warning that all category names are public.

**Comment by kevwu** [comment]
Reopening this issue: Only showing categories that are used on public posts is less trivial of a solution than I thought it would be.

I don't quite feel comfortable keeping all categories public - not all categories need to be broadcast to the world.

**Comment by kevwu** [comment]
[kev] i could do this: select * from categories where owner = [user id]; then using that returned data, foreach category view all posts in that category, and if there is even one public post then we can display that category entry.
[hillmonitor] Select the public posts first, then select * from categories join catmap where postId in (...)

**Comment by kevwu** [comment]
Categories now only display on your profile if contain public notes. Categories with only private notes, unlisted notes, or no notes at all will not be shown!

As always, only public notes are listed on your profile.
