### ISSUE TITLE
LaTeX showing up in code blocks when not intended

### ISSUE THREAD

**Issue by hamzacooly** [nanote-co/issues#34]
http://prntscr.com/9g8luw
Trying to write code in a code block explaining the printf() method, but it detects the '$' sign as LaTeX when it should be detecting it as code instead.

**Comment by kevwu** [comment]
This is a known issue, see for example issue #2 . I'll have to dig around Showdown, the Markdown renderer that Nanote uses, to find some way to stop LaTeX blocks from interfering with styling blocks.
