### ISSUE TITLE
Long category names cause display problems

### ISSUE THREAD

**Issue by bw** [nanote-co/issues#52]
![capture](https://cloud.githubusercontent.com/assets/4513630/15271314/85d0a1e4-1a08-11e6-8e14-3918cfd94208.PNG)

**Comment by kevwu** [comment]
I was afraid of this...

I'm not sure yet how to elegantly handle this. Just have them clip if they overflow, I suppose?

**Comment by kevwu** [comment]
Fixed, long category names now clip gracefully.: 
![image](https://cloud.githubusercontent.com/assets/937984/17540802/67e87198-5e87-11e6-97b2-ffa050bd1baa.png)
