### ISSUE TITLE
Request: Support password managers for login

### ISSUE THREAD

**Issue by timmc** [nanote-co/issues#7]
I think this might be as simple as putting a `<form>` around the input fields and capturing onsubmit.

**Comment by kevwu** [comment]
I've pushed a fix that should fix this. I don't use a password manager at the moment (I know, I know). Could you verify that this works for you?

**Comment by timmc** [comment]
Yes, that works for me, thanks! It's not a full solution, but I think it's fine for power users and maybe more than that.

There are two components to what a password manager might need, and this solves one of them (the more important one):

1. Detecting a login form requires `<input>` fields in a `<form>` with no `autocomplete=off`; if this is present, a password manager can offer to fill with an *existing* password.
2. Detecting a login submit event requires # 1 but also requires... I'm less sure here, I thought it was a submit event but it might require a click on a `<button>` in the form; if this is present, a password manager can offer to save a *new* password.

For whatever reason, # 2 isn't currently fulfilled, but I have an extension in Firefox that allows me to say "save the current contents of this form as a login", and subsequently Firefox will offer to fill the form. LastPass also provides this option. I'm not sure what other managers do.

So right now it allows a sufficiently determined password manager user to save passwords without too much trouble (but not fully automatically), and that's probably good enough for the moment.

**Comment by kevwu** [comment]
Google Chrome's autocomplete seems to also detect that this is a password field (it offers to save the password for me upon submission). I've also tried manually triggering a "submit" event on the form and it does indeed work the same as hitting enter or clicking "log in".

It looks like this works well enough, so I'll close this for now.

**Comment by timmc** [comment]
Cool! Glad to hear Chrome picks it up. Maybe newer Firefox does too, for that matter. I'm on the ESR channel.
